let debug = false;//开发和线上切换，true开发,线上false
var bu = "http://127.0.0.1:8101";

let mu = bu + "";

if (!debug){
	bu = "https://demo.modulithshop.cn";
	mu = bu + "";
}

let iu = bu + "/index.php";
let au = bu + "/account.php";

let su = bu + "/shop/static/src/default";
let cdn = 'https://static.shopsuite.cn';

let ip = bu + '';
// let ip = '/mobile/'
// let ip = 'https://demo.mallsuite.cn/mobile/'

export default {
	basePath: au,
	fileBasePath: bu,

	storeId: 1002,

	SiteUrl: bu,
	ApiUrl: bu,
	pagesize: 10,
	WapSiteUrl: bu + "/wap",
	AppDownloadUrl: bu + "/index.php?ctl=Mobile&met=download",

	WapStaticUrl: bu + "/wap",

	SiteLogo: bu + "/image.php/shop/data/upload/media/user/10001/image/20181106/1541507399271557.png",
	SiteIcon: bu + "/image.php/shop/data/upload/media/user/10001/image/20180828/1535448698303311.png",
	WapSiteLogo: bu + "/image.php/shop/data/upload/media/user/10001/image/20181106/1541507548407729.png",

	WechatStatus: 1,

	UPLOAD_TYPE: 'default', //aliyun

	CONFIG: {
		base_url: bu,
		index_url: iu,
		admin_url: mu,
		index_page: "index.php",
		static_url: cdn + "/shop/static/src/default",
		xhp_url: cdn + "/xhp"
	},

	HTTPS: 1,
	SYS_TYPE: 'multi',
	MULTISHOP_ENABLE: 1,
	EVALUATION_ENABLE: 1,
	SAAS_STATUS: 0,
	STORE_ID: 1001,
	VIRTUAL_ENABLE: 0,
	O2O_ENABLE: 1,
	CHAIN_ENABLE: 0,

	POINTS_VAUE_RATE: 1,
	SP_VAUE_RATE: 1,

	PLANTFORM_FX_ENABLE: 1,
	STORE_FX_ENABLE: 0,
	PLANTFORM_SP_PRIZE_ENABLE: 0,

	PLANTFORM_FX_AGENT_ENABLE: 0,
	PLANTFORM_FX_PT_ENABLE: 0,
	PLANTFORM_FX_WESTORE_ENABLE: 0,
	PLANTFORM_DELIVERY_TIME_ENABLE: 0,

	STORE_SUPPLIER_ENABLE: 1,
	PLANTFORM_REBATE_ENABLE: 0,



	PAOTUI_ENABLE: 1,
	USERSTOCK_ENABLE: 0,
	ORDERCONFIRM_ENABLE: 1,
	MARKETORDER_ENABLE: 1,


	REDPACKET_ENABLE: 0,
	CREDIT_ENABLE: 0,
	POINT_ENABLE: 1,
	SP_ENABLE: 0,

	EXCHANGECARD_ENABLE: 0,
	MONEY_TRANSFER_ENABLE: 0,

	SNS_ENABLE: 0,
	IM_ENABLE: 1,
	SUBSITE_ENABLE: 0,
	LANG_ENABLE: 0,
	FORCE_BIND_MOBILE: 0,
	SCAN_ENABLE: 0,

	CACHE: false,
	CACHE_EXPIRE: 3600 * 1,


	URL: {
		"listTranslateLang": ip + "/front/sys/config/listTranslateLang",
		"sysInfo": ip + "/front/sys/config/info",
		"getMobileIndexNav": ip + "/front/sys/page/getMobileIndexNav",
		"getMobilePage": ip + "/front/sys/page/getMobilePage",
		"index_guide": ip + "/front/sys/config/guide",

		verifyCode: ip + '/front/sys/captcha/index', // 获取登录验证码路径
		sendMobileVerifyCode: ip + '/front/sys/captcha/mobile',
		sendEmailVerifyCode: ip + '/front/sys/captcha/email',

		login: ip + '/front/account/login/login',
		register: ip + '/front/account/login/register',
		logout: ip + '/front/account/login/logout',
		doSmsLogin: ip + "/front/account/login/doSmsLogin",

		setNewPassword: ip + "/front/account/login/setNewPassword",

		userInfo: ip + '/front/account/user/info',

		upload: ip + '/front/sys/upload/index', // 图片 oss 路径
		testEmail: ip + '/manage/shop/email/testEmail', // 邮件测试路径

		area: ip + '/front/sys/district/tree',
		getDistrictTree: ip + "/front/sys/district/tree",

		pt: {
			listCategory: ip + "/front/pt/product/listCategory",
			treeCategory: ip + "/front/pt/product/treeCategory",
			list: ip + "/front/pt/product/list",
			guess: ip + "/front/pt/product/guess",
			listItem: ip + "/front/pt/product/listItem",

			listFilter: ip + "/front/pt/product/getSearchFilter",

			item: ip + "/front/pt/product/detail",
		},

		cart: {
			add: ip + "/front/trade/cart/add",
			list: ip + "/front/trade/cart/list",


			"remove": ip + "/front/trade/cart/remove",
			"removeBatch": ip + "/front/trade/cart/removeBatch",
			"removeItems": iu + "?ctl=Cart&met=removeItems&typ=json",
			"edit": iu + "?ctl=Cart&met=edit&typ=json",
			// "lists":iu + "?ctl=Cart&met=lists&typ=json",
			"listsMini": iu + "?ctl=Cart&met=listsMini&typ=json",
			// "quantity": iu + "?ctl=Cart&met=editQuantity&typ=json",
			"quantity": ip + "/front/trade/cart/editQuantity",
			"cookie": iu + "?ctl=Cart&met=getCookieCart&typ=json",
			"index": iu + "?ctl=Cart&met=index&typ=json",
			// "sel": iu + "?ctl=Cart&met=sel&typ=json",
			"sel": ip + "/front/trade/cart/sel",
			// "checkout": iu + "?ctl=Cart&met=checkout&typ=json",
			"checkout": ip + "/front/trade/cart/checkout",
			"checkDelivery": iu + "?ctl=Cart&met=checkDelivery&typ=json",
			"order": iu + "?ctl=Cart&met=order&typ=e",
			// "getselect":iu + "?ctl=Cart&met=getselect&typ=json",
			"getselect": ip + "/front/trade/cart/getSelect",
			"batchadd": ip + "/front/trade/cart/addBatch"
		},

		marketing:{
			listVoucher: ip + "/front/marketing/activityBase/listVoucher?activity_type_id=1105",
			list: ip + "/front/marketing/activityBase/list",
			listsGroupbookingActivity: ip + "/front/marketing/activityBase/listsGroupbookingActivity",
			listGroupbooking: ip + "/front/marketing/activityBase/listGroupbooking",
			listsUserGroupbookingHistory: ip + "/front/marketing/activityBase/listsUserGroupbookingHistory",
			getUserGroupbooking: ip + "/front/marketing/activityBase/getUserGroupbooking",
			getCutpriceActivity: ip + "/front/marketing/activityBase/getCutpriceActivity",
			listsCutpriceHistory: ip + "/front/marketing/activityBase/listsCutpriceHistory",
			doCutprice: ip + "/front/marketing/activityBase/doCutprice",
			getActivityInfo :ip + "/front/marketing/activityBase/getActivityInfo",
		},
		
		edu:{
			getLecturerList :ip + "/front/edu/userLecturer/list",
			getLecturerDetail :ip + "/front/edu/userLecturer/getLecturerDetail",
			
			getSubscribeList :ip + "/front/edu/subscribeLecturer/getSubscribeList",
			isSubscribe :ip + "/front/edu/subscribeLecturer/isSubscribe",
			subscribeLecturer :ip + "/front/edu/subscribeLecturer/editSubscribe",
			getCategoryList :ip + "/front/edu/course/getCategoryList",
			getLearnTime :ip + "/front/edu/learnTarget/getLearnTime",
			setLearnTarget :ip + "/front/edu/learnTarget/setLearnTarget",
			getLearnTarget :ip + "/front/edu/learnTarget/getLearnTarget",
			getBuyCourseList:ip + "/front/edu/course/getBuyCourseList",
			saveCourseStock:ip + "/front/edu/course/saveCourseStock",
			getCourseList: ip + "/front/edu/course/list",
			getProductItem :ip + "/front/pt/product/detail",
			
			getTopicListByPaperId :ip + "/front/edu/course/getTopicListByPaperId",
			getChapter :ip + "/front/edu/course/getChapter",
			saveChapterStock :ip + "/front/edu/course/saveChapterStock",
			saveExam :ip + "/front/edu/exam/saveExam",
		},

		"shop_list_category":ip+"shop/shop-base-product-category/category",
		"shop_list_category_product":ip+"shop/shop-gif-list-form/getGiftList",
		// "index": iu + "?ctl=Mobile&met=mobile&typ=json"
		"index": iu + "?ctl=Mobile&met=mobile&typ=json",
		"index_mobile": iu + "?ctl=Mobile&met=mobile&typ=json",
		// "getMobilePage": iu + "?ctl=Mobile&met=app&typ=json",
		// "index_guide": iu + "?ctl=Mobile&met=guide&typ=json",
		"story_category": iu + "?ctl=Mobile&met=storyCategory&typ=json",
		// "subsite_list": iu + "?ctl=Mobile&met=getSubsite&typ=json",
		"subsite_list": ip + "shop/mobile/getSubsite",
		// "upload": iu + "?ctl=Media&met=uploadImage&typ=json",
		// "upload_file": iu + "?ctl=Media&met=uploadFile&typ=json",
		"upload_file": ip + "shop/oss/upload",
		"upload_scrawl": iu + "?ctl=Media&met=uploadScrawl&typ=json",
		"upload_config": iu + "?ctl=Media&met=config&typ=json",
		"uptoken": iu + "?ctl=Media&met=uptoken&typ=json",
		// "info":iu + "?ctl=Mobile&met=info&typ=json",
		"update_app": iu + "?ctl=Mobile&met=updateApp&typ=json",
		"page": iu + "?ctl=Page&met=get&typ=json",

		// "survey": iu + "?ctl=Page&met=doSurvey&typ=json",
		"survey": ip + "shop/page/doSurvey",
		"doSurveyList": ip + "shop/page/doSurveyList",
		"doSurveyOne": ip + "shop/page/doSurveyOne",
		"doSurveyDel": ip + "shop/page/doSurveyDel",
		"qrcode": bu + "/shop/api/qrcode.php",
		// "getAppDistrict":iu + "?ctl=Mobile&met=getAppDistrict&typ=json",
		// "filter_opt":iu + "?ctl=Mobile&met=getFilterOpt&typ=json",
		"filter_opt": ip + "shop/store/getFilterOpt",

		// "productfilter_opt": iu + "?ctl=Mobile&met=getFilterProdcutOpt&typ=json",
		"productfilter_opt": ip + "shop/shop-product-base/getFilterProdcutOpt",
		"product": {
			// "item":iu + "?ctl=Product&met=item&typ=json",
			"item_list": ip + "shop/shop-product-item/list",
			// "quick": iu + "?ctl=Product&met=quick&typ=json",
			"quick": ip + "shop/shop-product-base/quick",
			"info": iu + "?ctl=Product&met=info&typ=json",
			"lists": ip + "shop/shop-product-base/lists",
			"guess": ip + "shop/shop-product-base/guessyoulike",
			"auto_complete": iu + "?ctl=Product&met=listName&typ=json",
			// "shipping_district": iu + "?ctl=Product&met=shippingDistrict&typ=json",
			"shipping_district": ip + "shop/shop-product-base/shippingDistrict",
			// "category":iu + "?ctl=Product&met=category&typ=json",
			// "brand": iu + "?ctl=Product&met=brand&typ=json",
			"brand": ip + "shop/shop-product-base/brand",
			"brand_list": mu + "/admin/shop/shop-base-product-brand/getBrandList",
			"all_brands": mu + "/admin/shop/shop-base-product-brand/brands",
			"list_brands": iu + "?ctl=Product&met=listsBrands&typ=json",
			"list_brands_products": iu + "?ctl=Product&met=listsBrandsAndProducts&typ=json",
			// "product_comment":iu + "?ctl=Product&met=comment&typ=json",

			"product_comment": ip + "/front/pt/product/getComment",
			"add_comment_reply": iu + "?ctl=Product&met=addCommentReply&typ=json",
			"comment_helpful": iu + "?ctl=Product&met=commentHelpful&typ=json",
			"faq": iu + "?ctl=Product&met=faq&typ=json",
			"popular": iu + "?ctl=Product&met=productPopular&typ=json",
			"spec": iu + "?ctl=Product&met=getSpec&typ=json",


			"list_stores": iu + "?ctl=PlanformActivity&met=listsStores&typ=json",
			"list_stores_products": iu + "?ctl=PlanformActivity&met=listsStoresProducts&typ=json",
			/*"list_brands":iu + "?ctl=PlanformActivity&met=listsBrands&typ=json",
			"list_brands_products":iu + "?ctl=PlanformActivity&met=listsStoresProducts&typ=json",*/
			// "list_times": iu + "?ctl=PlanformActivity&met=listsTimes&typ=json",
			"list_times": ip + "shop/Activity/listsTimes",
			"list_times_products": iu + "?ctl=PlanformActivity&met=listsTimeProduct&typ=json",
			"getProductOne": ip + "shop/shop-product-base/getProduct",
			"getProductDetail": ip + "shop/shop-product-detail/getProductDetail",
			"getServiceTemplateById": mu +"/admin/shop/service/template/service-template/getServiceTemplate",
			"getServiceTemplateDetails": mu +"/admin/shop/service/template/service-template-detail/list",
			"getDetailList": mu +"/admin/shop/service/template/service-template-detail/getDetailList",
			"getShareData": ip + "shop/shop-product-item/getShareData",
			"addShareNum": ip + 'shop/userOrder/addShareNum'
		},
		"loginInfo": iu + "?ctl=Index&met=getLoginInfo&typ=json",
		//"search_filter": iu + "?ctl=Mobile&met=getSearchFilter&typ=json",
		"district": iu + "?ctl=Mobile&met=district&typ=json",
		"district_all": iu + "?ctl=Mobile&met=getAllDistrict&typ=json",
		"district_id": iu + "?ctl=Mobile&met=getDistrictByName&typ=json",
		"search_hot_info": ip + "/front/shop/mobile/getSearchInfo",
		// "search_hot_info": iu + "?ctl=Mobile&met=getSearchInfo&typ=json",
		"connect": ip + "account/login/getConnectInfo",
		"login_box": au + "?ctl=Login&met=index&typ=e&login_box=1",


		// "logout": au + "?ctl=Login&met=logout&typ=json",
		"check_mobile_or_email": au + "?ctl=Login&met=checkMobileOrEmail&typ=json",
		// "protocol": au + "?ctl=Login&met=protocol&typ=json",
		"protocol": ip + "/front/account/login/protocol",
		"check_login": au + "?ctl=Login&met=checkLogin&typ=json",
		// "check_islogin": au + "?ctl=Login&met=ifLogin&typ=json",
		"check_islogin": ip + "account/login/ifLogin",

		//"do_app_login": au + "?ctl=Login&met=doAppConnectLogin&typ=json&flag=app",
		"do_app_login": ip + "account/login/doAppConnectLogin",

		"check_app_login": au + "?ctl=Login&met=checkAppConnectLogin&typ=json&flag=app",
		// "get_miniapp_open_id": au + "?ctl=Login&met=getOpenIdByCode&typ=json",
		"get_miniapp_open_id": ip + "/front/account/wechat/getOpenIdByCode",

		"register_wechat_account": au + "?ctl=Login&met=doRegisterWechatAccount&typ=json",
		"find_pwd_s2": au + "?ctl=Login&met=findpwdStepTwo&typ=e&step=2",
		"find_pwd_s3": au + "?ctl=Login&met=findpwdStepThree&typ=e&step=3",
		// "delivery_info": bu + "/shop/api/delivery.php",
		"delivery_info": ip + "/front/trade/orderLogistics/trace",
		"download_proxy": "https://test.suteshop.com/shop/api/download.php",
		"account": {
			bindMobile: ip + "/front/account/user/bindMobile",
			reBindMobile: ip + "/front/account/user/reBindMobile",
			unBindMobile: ip + "/front/account/user/unBindMobile",

			// "certificate": au + "?ctl=User_Security&met=certification&typ=e",
			"certificate": ip + "account/userSecurity/certification",
			"typeList": au + "?ctl=User_Account&met=getUserType&typ=e",
			"get_mobile_info": au + "?ctl=User_Security&met=index&typ=json",
			"check_security_change": au + "?ctl=User_Security&met=checkSecurityChange&typ=json",

			"edit_user_info": ip + "/front/account/user/edit",
			"saveCertificate": ip + "/front/account/user/saveCertificate",
			"listBaseUserLevel": ip + "/front/account/user/listBaseUserLevel",
			"listsExpRule": ip + "/front/account/user/listsExpRule",
			// "edit_user_sign": au + "?ctl=User_Account&met=sign&typ=json",
			"edit_user_sign": ip + "account/user/editSign",
			"get_card_qrcode": au + "?ctl=User_Account&met=getCardQrcode&typ=e"
		},
		"wx": {
			"share": au + "?ctl=Connect_Weixin&met=share&typ=e",
			// "config": au + "?ctl=Connect_Weixin&met=wxConfig&typ=e&body_class_none=1",
			"config": ip + "/front/account/wechat/wxConfig",
			"pay_config": au + "?ctl=Connect_Weixin&met=wxPayConfig&typ=json",
			//"mplogin": au + "?ctl=Connect_Weixin&met=login&typ=e&flag=mp",
			"mplogin": ip + "/front/account/wechat/redirectToWxCode",
			"checkMpH5Login": ip + "/front/account/wechat/callbackMp",
			"openlogin": au + "?ctl=Connect_Weixin&met=login&typ=e&flag=open",
			// "applogin": au + "?ctl=Connect_Weixin&met=jscode2session&typ=json&flag=app",
			"applogin": ip + "/front/account/wechat/jsCode2Session",
			// "editinfo": au + "?ctl=Connect_Weixin&met=jscode2session&typ=json&flag=app",
			"editinfo": ip + "/front/account/wechat/jsCode2Session",
			// "checkAppLogin": au + "?ctl=Connect_Weixin&met=checkAppLogin&typ=json&flag=app",
			"checkAppLogin": ip + "/front/account/wechat/checkAppLogin",
			"getQRCode": au + "?ctl=Connect_Weixin&met=getQRCode&typ=json&flag=app",
			"getMiniAppQRCode": au + "?ctl=Connect_Weixin&met=getMiniAppQRCode&typ=json&flag=app",
			"getMiniAppQRCodeUnlimit": au + "?ctl=Connect_Weixin&met=getMiniAppQRCodeUnlimit&typ=json&flag=app",
			// "getMiniAppQRCodeUnlimitPoster": au +
			// 	"?ctl=Connect_Weixin&met=getMiniAppQRCodeUnlimitPoster&typ=json&flag=app",
			"getMiniAppQRCodeUnlimitPoster": ip + "shop/distributionUser/poster?poster_type=2",
			"pay": bu + "/account/modules/pay/api/payment/wx/pay.php",
			"get_tpl_msg_config": au + "?ctl=Connect_Weixin&met=getTmpMsgConfig&typ=json&flag=app",
			"send_tpl_msg": au + "?ctl=Connect_Weixin&met=sendTplMsg&typ=json&flag=app",
			"get_user_phone_number": ip + "/front/account/wechat/getUserPhoneNumber"
		},
		"chain": {
			"getChain": ip + "/front/o2o/chain/getChainInfo",
			"listsChainProduct": ip + "/front/o2o/chain/listChainProduct",
			"getNearChain": ip + "/front/o2o/chain/list",
		},
		"store": {
			"get": iu + "?ctl=Store&met=get&typ=json",
			// "add": iu + "?ctl=Store&met=add&typ=json",
			"add": ip + "shop/store/add",
			"credit": iu + "?ctl=Store&met=credit&typ=json",
			// "info":iu + "?ctl=Store&met=info&typ=json",
			"info": ip + "shop/store/info",
			// "contents":iu + "?ctl=Store&met=contents&typ=json",
			"contents": ip + "shop/store/contents",
			// "index_diy": iu + "?ctl=Store&met=indexDiy&typ=json",
			"index_diy": ip + "shop/page/index_diy",
			"profile": iu + "?ctl=Store&met=profile&typ=json",
			"menu": iu + "?ctl=Store&met=menu&typ=json",
			// "lists":iu + "?ctl=Store&met=lists&typ=json",
			"lists": ip + "shop/store/lists",

			"listsChain": iu + "?ctl=Chain&met=lists&typ=json",
			// "getChain":iu + "?ctl=Chain&met=getChainInfo&typ=json",
			"getChain": ip + "shop/shop-chain-base/getChainInfo",
			"listsChainItems": iu + "?ctl=Chain&met=listsChainItems&typ=json",
			// "listsChainProduct": iu + "?ctl=Chain&met=listsChainProduct&typ=json",
			"listsChainProduct": ip + "shop/shop-chain-base/listsChainProduct",
			"listChainByItem": iu + "?ctl=Chain&met=listChainByItem&typ=json",
			// "getNearChain":iu + "?ctl=Chain&met=getNearChain&typ=json",
			"getNearChain": ip + "shop/shop-chain-base/getNearChain",

			"isDefautChain": iu + "?ctl=Chain&met=isDefautChain&typ=json",
			"setChain": iu + "?ctl=Chain&met=setChain&typ=json",

			"near": iu + "?ctl=Store&met=lists&typ=json",
			// "category": iu + "?ctl=Store&met=category&typ=json",
			"category": ip + "shop/store/category",
			// "activity":iu + "?ctl=Store&met=activity&typ=json",
			"activity": ip + "shop/store/activity",
			// "product":iu + "?ctl=Product&met=lists&typ=json",
			"product": ip + "shop/shop-product-base/lists",
			"item": iu + "?ctl=Product&met=lists&typ=json",
			// "product_category":iu + "?ctl=Store&met=productCategory&typ=json",
			"product_category": ip + "shop/store/productCategory",
			"product_popular": iu + "?ctl=Store&met=productPopular&typ=json",
			"lists_store_grade": iu + "?ctl=Store&met=listsStoreGrade&typ=json",
			// "lists_store_category": iu + "?ctl=Store&met=listsStoreCategory&typ=json",
			"lists_store_category": ip + "shop/store/listsStoreCategory",
			"commit_payment_voucher": iu + "?ctl=Store&met=paymentVoucher&typ=json",
			"survey": iu + "?ctl=Store&met=doSurvey&typ=json",
			"lists_groupbuy_store": iu + "?ctl=Activity&met=listsGroupBuyStore&typ=json"
		},
		"point": {
			// "voucher": iu + "?ctl=Point&met=voucher&typ=json",
			// "index": iu + "?ctl=Point&met=index&typ=json",
			"index": ip + "shop/point/index",
			"product_detail": iu + "?ctl=Point&met=productDetail&typ=json",
			// "product": iu + "?ctl=Point&met=product&typ=json"
			"product": ip + "/front/pt/product/list"
		},
		"verify": {
			"image": au + "?ctl=VerifyCode&met=image&typ=json",
			// "mobile": au + "?ctl=VerifyCode&met=mobile&typ=json",
			"mobile": ip + "account/user/verifyCode",
			// "email": au + "?ctl=VerifyCode&met=email&typ=json"
			"email": ip + "account/user/verifyCode",
		},
		"diy": {
			"fonts": iu + "?mdu=diy&ctl=Diy&met=getFonts&typ=json",
			"getFonts": iu + "?mdu=diy&ctl=Diy&met=getFonts&typ=json",
			"getCartFileUrl": iu + "?mdu=diy&ctl=Diy&met=getCartFileUrl&typ=json",
			"getModelShowUrl": iu + "?mdu=diy&ctl=Diy&met=getModelShow&typ=json",
			"getItemSkuColorShowUrl": iu + "?mdu=diy&ctl=Diy&met=getItemSkuColorShowUrl&typ=json",
			"getTypeBasesByParentUrl": iu + "?mdu=diy&ctl=Diy&met=getMaterialCategory&typ=json",
			"queryOriginalByCategoryUrl": iu + "?mdu=diy&ctl=Diy&met=getMaterial&typ=json",
			"removeBgColor": iu + "?mdu=diy&ctl=Diy&met=removeBgColor&typ=json",
			"getStyleUrl": iu + "?mdu=diy&ctl=Diy&met=getStyleUrl&typ=json",
			"imgstyUrl": iu + "?mdu=diy&ctl=Diy&met=getImageStyleUrl&typ=json",
			"getUserDiyGoodsSkuListUrl": iu + "?mdu=diy&ctl=Diy&met=getUserDiyGoodsSkuListUrl&typ=json",
			"saveDiyGoodsAndAddShopCartUrl": iu + "?mdu=diy&ctl=Diy&met=saveDiyGoodsAndAddShopCartUrl&typ=json",
			"upload": iu + "?mdu=diy&ctl=Diy&met=uploadImage&typ=json",
			"upload_file": iu + "?mdu=diy&ctl=Diy&met=uploadFile&typ=json",
			"upload_scrawl": iu + "?mdu=diy&ctl=Diy&met=uploadScrawl&typ=json",
			"upload_scrawl_diy": iu + "?mdu=diy&ctl=Diy&met=uploadScrawlDiy&typ=json",
			"upload_config": iu + "?mdu=diy&ctl=Diy&met=config&typ=json",
			"uptoken": iu + "?mdu=diy&ctl=Diy&met=uptoken&typ=json",
			"getDespLists": iu + "?mdu=diy&ctl=Diy&met=getDespLists&typ=json",
			"buyGoodsUrl": iu + "?mdu=diy&ctl=Diy&met=buyGoodsUrl&typ=json",
			"getDesignList": iu + "?mdu=diy&ctl=Diy&met=getDesignList&typ=json",
			"getDiyMaskListUrl": iu + "?mdu=diy&ctl=Diy&met=getDiyMaskList&typ=json",
			"getAllColorUrl": iu + "?mdu=diy&ctl=Diy&met=getAllColorUrl&typ=json",
			"getTechnicsListUrl": iu + "?mdu=diy&ctl=Diy&met=getTechnicsListUrl&typ=json",
			"getTechnicsPriceUrl": iu + "?mdu=diy&ctl=Diy&met=getTechnicsPriceUrl&typ=json",
			"searchMaterialsUrl": iu + "?mdu=diy&ctl=Diy&met=searchMaterialsUrl&typ=json"
		},
		"cms": {
			// "lists": iu + "?mdu=cms&ctl=Article&met=lists&typ=json",
			"lists": ip + "/front/cms/articleBase/list",
			"category": ip + "/front/cms/articleBase/listCategory",
			// "get": iu + "?mdu=cms&ctl=Article&met=get&typ=json",
			"get": ip + "/front/cms/articleBase/get",
			"add_article_comment": iu + "?mdu=cms&ctl=Article&met=addComment&typ=json",
			"add_article_comment_reply": iu + "?mdu=cms&ctl=Article&met=addCommentReply&typ=json",
			"get_related_article": iu + "?mdu=cms&ctl=Article&met=getRelatedArticle&typ=json",
			"comment_helpful": iu + "?mdu=cms&ctl=Article&met=commentHelpful&typ=json",
			"remove_comment_helpful": iu + "?mdu=cms&ctl=Article&met=removeCommentHelpful&typ=json",
			"comment_reply_helpful": iu + "?mdu=cms&ctl=Article&met=commentReplyHelpful&typ=json",
			"remove_comment_reply_helpful": iu + "?mdu=cms&ctl=Article&met=removeCommentReplyHelpful&typ=json"
		},
		user : {
			address_edit: ip + "/front/account/userDeliveryAddress/save",
			address_add: ip + "/front/account/userDeliveryAddress/add",
			address_lists: ip + "/front/account/userDeliveryAddress/list",
			address_remove: ip + "/front/account/userDeliveryAddress/remove",
			address_get: ip + "/front/account/userDeliveryAddress/get",


			listBrowser: ip + "/front/shop/userProductBrowse/list",
			removeBrowser: ip + "/front/shop/userProductBrowse/removeBrowser",

			removeWishItem: ip + "/front/shop/userFavoritesItem/remove",
			listWishItem: ip + "/front/shop/userFavoritesItem/lists",
			addWishItem: ip + "/front/shop/userFavoritesItem/add",

			"wish_brand_lists": ip + "/front/pt/favoritesBrand/lists?action=brand",
			"wish_brand_remove": ip + "shop/favorites/remove?action=brand",
			"wish_brand_add": iu + "shop/favorites/add?action=brand",


			getOrderNum: ip + "/front/trade/order/getOrderNum",

			points: ip + "/front/pay/points/list",


			"msg_count": ip + "/front/account/userMessage/getMsgCount",
			// "msg_config": au + "?ctl=Index&met=getConfig&typ=json",
			"msg_config": ip + "/front/account/userMessage/getImConfig",
			//"kefu_config": au + "?ctl=Index&met=getKefuConfig&typ=json",
			kefu_config: ip + "/front/account/userMessage/getKefuConfig",
			// "msg_lists": au + "?mdu=sns&ctl=User_Message&met=lists&typ=json",
			"msg_lists": ip + "/front/account/userMessage/list",
			// "msg_chat_lists": au + "?mdu=sns&ctl=User_Message&met=listChatMsg&typ=json",
			"msg_chat_lists": ip + "/front/account/userMessage/listChatMsg",
			// "msg_get": au + "?mdu=sns&ctl=User_Message&met=get&typ=json",
			"msg_get": ip + "/front/account/userMessage/get",
			// "msg_set_read": au + "?mdu=sns&ctl=User_Message&met=setRead&typ=json",
			"msg_set_read": ip + "/front/account/userMessage/setRead",
			"zonemsg_lists": au + "?mdu=sns&ctl=User_ZoneMessage&met=lists&typ=json",
			"zonemsg_add_msg": au + "?mdu=sns&ctl=User_ZoneMessage&met=addMessage&typ=json",
			"msg_user_lists": au + "?mdu=sns&ctl=User_Message&met=getMsgUser&typ=json",
			// "msg_add": au + "?mdu=sns&ctl=User_Message&met=add&typ=json",
			"msg_add": ip + "/front/account/userMessage/add",
			"msg_remove": au + "?mdu=sns&ctl=User_Message&met=remove&typ=json",
			"msg_remove_user": au + "?mdu=sns&ctl=User_Message&met=removeUserMsg&typ=json",
			"msg_notice_lists": au + "?mdu=sns&ctl=User_Message&met=listNotice&typ=json",
			// "lists_base_level": au + "?mdu=sns&ctl=Index&met=listBaseUserLevel&typ=json",
			"friend_info_lists": au + "?mdu=sns&ctl=User_Friend&met=getFriendsInfo&typ=json",
			// "friend_agree": au + "?mdu=sns&ctl=User_Friend&met=agree&typ=json",
			"friend_agree": ip + "sns/userFriend/agree",
			// "friend_refuse": au + "?mdu=sns&ctl=User_Friend&met=refuse&typ=json",
			"friend_refuse": ip + "sns/userFriend/refuse",
			"more_comment": iu + "?ctl=User_Comment&met=loadMoreComment&typ=json",
			"add_product_comment": iu + "?ctl=User_Comment&met=add&typ=json",
			// "add_order_comment": iu + "?ctl=User_Order&met=addOrderComment&typ=json",
			"add_order_comment": ip + "/front/trade/order/addOrderComment",
			"ask_helpful": iu + "?ctl=User_Ask&met=hasHelpful&typ=json",
			"ask_add": iu + "?ctl=User_Ask&met=add&typ=json",
			// "edit": iu + "?ctl=User_Account&met=edit&typ=json",
			"edit": ip + "/front/account/user/edit",
			"lists": iu + "?ctl=User_Account&met=lists&typ=json",
			// "points": iu + "?ctl=User_Resource&met=pointsHistory&typ=json",
			"money2points": iu + "?ctl=User_Resource&met=money2Points&typ=json",
			"points2money": iu + "?ctl=User_Resource&met=points2Money&typ=json",
			// "signState": iu + "?ctl=User_Resource&met=signState&typ=json",
			"signState": ip + "/front/pay/userResource/signState",
			"resource": iu + "?ctl=User_Resource&met=resource&typ=json",
			// "signIn": iu + "?ctl=User_Resource&met=signIn&typ=json",
			"signIn": ip + "/front/pay/userResource/signIn",
			"listsExp": ip + "/front/pay/userResource/listsExp",
			//"getSignInfo":iu + "?ctl=User_Resource&met=getSignInfo&typ=json",
			"getSignInfo":ip + "/front/pay/userResource/getSignInfo",
			"getCommissionInfo":ip + "/front/pay/userResource/getCommissionInfo",
			"lists_chain_code": iu + "?ctl=User_Resource&met=listsChainCode&typ=json",
			"lists_voucher_product": iu + "?ctl=User_Voucher&met=listsVoucherProduct&typ=json",
			// "voucherList": iu + "?ctl=User_Voucher&met=lists&typ=json",
			"voucherList": ip + "/front/shop/userVoucher/list",
			// "voucher_get": iu + "?ctl=Activity&met=getVoucher&typ=json",
			"voucher_get": ip + "/front/shop/userVoucher/get",
			"voucherNum": iu + "?ctl=User_Voucher&met=getVoucherNum&typ=json",
			// "eachVoucherNum": iu + "?ctl=User_Voucher&met=getEachVoucherNum&typ=json",
			"eachVoucherNum": ip + "/front/shop/userVoucher/getEachVoucherNum",
			// "voucher_add": iu + "?ctl=User_Voucher&met=add&typ=json",
			"voucher_add": ip + "/front/shop/userVoucher/add",
			"voucher_used": iu + "?ctl=User_Voucher&met=checkVoucher&typ=json",
			"voucher_offline": iu + "?ctl=User_Voucher&met=addOffline&typ=json",
			"receive_new_gift": iu + "?ctl=User_Voucher&met=receiveGift&typ=json",
			// "return_lists":iu + "?ctl=User_Return&met=lists&typ=json",
			"return_lists": ip + "/front/trade/orderReturn/list",
			"return_add": iu + "?ctl=User_Return&met=add&typ=json",
			// "return_add_one": iu + "?ctl=User_Return&met=addItem&typ=json",
			"return_add_one": ip + "/front/trade/orderReturn/add",
			// "return_item": iu + "?ctl=User_Return&met=returnItem&typ=json",
			"return_item": ip + "/front/trade/orderReturn/returnItem",
			// "return_cancel": iu + "?ctl=User_Return&met=cancel&typ=json",
			"return_cancel": ip + "/front/trade/orderReturn/cancel",
			// "return_get": iu + "?ctl=User_Return&met=get&typ=json",
			"return_get": ip + "/front/trade/orderReturn/get",
			// "return_tracking":iu + "?ctl=User_Return&met=returnTrackingNumber&typ=json",
			"return_tracking": ip + "/front/trade/orderReturn/edit",
			"return_confirm_refund": iu + "?ctl=User_Return&met=confirmRefund&typ=json",
			"invoice_type": iu + "?ctl=User_Invoice&met=type&typ=json",
			// "invoice_lists": iu + "?ctl=User_Invoice&met=lists&typ=json",
			"invoice_lists": ip + "/front/account/userInvoice/list",
			// "invoice_add": iu + "?ctl=User_Invoice&met=add&typ=json",
			"invoice_add": ip + "/front/account/userInvoice/add",
			// "invoice_edit": iu + "?ctl=User_Invoice&met=edit&typ=json",
			"invoice_edit": ip + "/front/account/userInvoice/edit",
			// "invoice_get": iu + "?ctl=User_Invoice&met=get&typ=json",
			"invoice_get": ip + "/front/account/userInvoice/get",
			// "invoice_remove": iu + "?ctl=User_Invoice&met=remove&typ=json",
			"invoice_remove": ip + "/front/account/userInvoice/remove",

			listOrderInvoice: ip + "/front/trade/order/listInvoice",

			"add_point_shopping_order": iu + "?ctl=User_Order&met=addPointShoppingOrder&typ=json",
			// "order_add": iu + "?ctl=User_Order&met=add&typ=json",
			"order_add": ip + "/front/trade/order/add",
			// "order_lists":iu + "?ctl=User_Order&met=lists&typ=json",
			"order_lists": ip + "/front/trade/order/list",
			// "order_cancel": iu + "?ctl=User_Order&met=cancel&typ=json",
			"order_cancel": ip + "/front/trade/order/cancel",
			// "order_receive": iu + "?ctl=User_Order&met=receive&typ=json",
			"order_receive": ip + "/front/trade/order/receive",
			"order_remove": iu + "?ctl=User_Order&met=remove&typ=json",
			// "order_detail":iu + "?ctl=User_Order&met=detail&typ=json",
			"order_detail": ip + "/front/trade/order/detail",

			"order_delivery": iu + "?ctl=User_Order&met=delivery&typ=json",
			"order_index": iu + "?ctl=User_Order&met=index&typ=e",
			"order_comment_manage": iu + "?ctl=User_Order&met=storeCommentManage&typ=json",
			// "order_comment_with_content": iu + "?ctl=User_Order&met=storeEvaluationWithContent&typ=json",
			"order_comment_with_content": ip + "/front/trade/order/storeEvaluationWithContent",
			"order_comment_add": iu + "?ctl=User_Order&met=addOrderComment&typ=json",
			"wish_store_lists": ip + "shop/favorites/lists?action=store",
			// "wish_store_remove": iu + "?ctl=User_Favorites&met=remove&typ=json&action=store",
			"wish_store_remove": ip + "shop/favorites/remove?action=store",



			"wish_store_get": iu + "?ctl=User_Favorites&met=get&typ=json&action=store",
			// "wish_store_add": iu + "?ctl=User_Favorites&met=add&typ=json&action=store",
			"wish_store_add": ip + "shop/favorites/add?action=store",


			// "feedback_add": iu + "?ctl=User_Feedback&met=add&typ=json",
			"feedback_add": ip + "/front/sys/feedback/add",
			// "feedback_lists": iu + "?ctl=User_Feedback&met=lists&typ=json",
			"feedback_lists": ip + "/front/sys/feedback/list",
			// "feedback_category": iu + "?ctl=User_Feedback&met=getCategory&typ=json",
			"feedback_category": ip + "/front/sys/feedback/getCategory",
			"check_wechat_address": iu + "?ctl=User_DeliveryAddress&met=checkWeChatAddress&typ=json",
			// "address_add": iu + "?ctl=User_DeliveryAddress&met=save&typ=json",

			"address_manage": iu + "?ctl=User_DeliveryAddress&met=manage&typ=e",
			// "joinIn": iu + "?ctl=Join&met=step&typ=e",
			"joinIn": ip + "shop/join/step",
			// "listsLottery": iu + "?ctl=User_Activity&met=getLottery&typ=json",
			"listsLottery": ip + "shop/userActivity/getLottery",
			// "doLottery": iu + "?ctl=User_Activity&met=doLottery&typ=json",
			"doLottery": ip + "shop/userActivity/doLottery",
			// "listsLotteryHistory": iu + "?ctl=User_Activity&met=listsLotteryHistory&typ=json",
			"listsLotteryHistory": ip + "shop/userActivity/listsLotteryHistory",
			//"getLotteryHistory": iu + "?ctl=User_Activity&met=getLotteryHistory&typ=json",
			"getLotteryHistory": ip + "shop/userActivity/getLotteryHistory",
			//"updateLotteryAddress": iu + "?ctl=User_Activity&met=updateLotteryAddress&typ=json",
			"updateLotteryAddress": ip + "shop/userActivity/updateLotteryAddress",
			// "listsMarketing": iu + "?ctl=User_Activity&met=listsMarketing&typ=json",
			"listsMarketing": ip + "shop/userActivity/listsMarketing",
			"listsUserMarketing": iu + "?ctl=User_Activity&met=listsUserMarketing&typ=json",
			// "getMarketing": iu + "?ctl=User_Activity&met=getMarketing&typ=json",
			"getMarketing": ip + "shop/userActivity/getMarketing",
			"doMarketing": iu + "?ctl=User_Activity&met=doMarketing&typ=json",
			// "listsUserCutPriceHistory": iu + "?ctl=User_Activity&met=listsUserCutPriceHistory&typ=json",
			"listsUserCutPriceHistory": ip + "shop/userActivity/listsUserCutPriceHistory",
			"listsCutPriceActivity": iu + "?ctl=Activity&met=listsCutPriceActivity&typ=json",

			// "direct_store_add": iu + "?ctl=User_DistributionStoreDirectsellerProduct&met=add&typ=json",
			"direct_store_add": ip + "shop/userDistributionStoreDirectseller/add",
			"direct_store_lists": iu + "?ctl=User_DistributionStoreDirectsellerProduct&met=index&typ=json",
			"direct_store_remove": iu + "?ctl=User_DistributionStoreDirectsellerProduct&met=remove&typ=json",
			// "direct_store_index": iu + "?mdu=distribution&ctl=WeStore&met=index&typ=json",
			"direct_store_index": ip + "shop/webStore/index",
			"listsUserVideo": iu + "?ctl=User_Order&met=listsUserVideo&typ=json",
			"serviceMessage": iu + "?ctl=Info&met=index&typ=json",
			"addServiceMessage": iu + "?ctl=User_Info&met=add&typ=json",
			"get_activity_code": mu + "/admin/shop/shop-store-activity-base/getActivityCodeList",
			"getDriverModel": mu + "/admin/shop/shop-product-driver-model/list",
			"saveDriverUserInfo": mu + "/admin/shop/shop-order-user-form/edit",
			"saveOrderAddEmail": ip + "shop/userOrder/orderAddEmail",
			"order_delete": ip + "shop/userOrder/orderDelete",
			"next_order": ip + "shop/userOrder/next_order",
			"getListGrLbt": ip + "account/config/list",
			"getListGrLbts": ip + "shop/userOrder/browser",
		},
		"pay": {
			moneyPay: ip + "/front/pay/consumeDeposit/moneyPay", //余额支付
			offlinePay: ip + "/front/pay/consumeDeposit/offlinePay", //offlinePay
			wechatAppletPay: ip + "/front/pay/consumeDeposit/wechatAppletPay", //微信小程序支付
			wechatAppPay: ip + "/front/pay/consumeDeposit/wechatAppPay", //微信Aapp支付
			wechatJSAPIPay: ip + "/front/pay/consumeDeposit/wechatJSAPIPay", //微信JS API
			wechatH5Pay: ip + "/front/pay/consumeDeposit/wechatH5Pay", //微信H5
			alipPay: ip + "/front/pay/consumeDeposit/alipayPay", //支付宝 API


			consumeRecord: ip + "/front/pay/consumeRecord/list",

			"type": au + "?mdu=pay&ctl=Index&met=payType&typ=json",
			"lists": au + "?mdu=pay&ctl=Index&met=payLists&typ=json",
			// "recharge": au + "?mdu=pay&ctl=Index&met=recharge&typ=json",
			"recharge": ip + "pay/index/recharge",
			"recharge_level": au + "?mdu=pay&ctl=Index&met=rechargeByLevel&typ=json",
			// "recharge_list": au + "?mdu=pay&ctl=Index&met=listRechargeLevel&typ=json",
			"recharge_list": ip + "/front/pay/index/listRechargeLevel",
			"favorable": au + "?mdu=pay&ctl=Index&met=favorable&typ=json",
			"other": au + "?mdu=pay&ctl=Index&met=other&typ=json",
			// "pay": au + "?mdu=pay&ctl=Index&met=pay&typ=json",

			"check_pay_passwd": au + "?mdu=pay&ctl=Index&met=checkPayPasswd&typ=json",
			// "get_pay_passwd": au + "?mdu=pay&ctl=Index&met=getPayPasswd&typ=json",
			"get_pay_passwd": ip + "/front/pay/index/getPayPasswd",
			// "asset": au + "?mdu=pay&ctl=Index&met=resourceIndex&typ=json",
			"asset": ip + "/front/pay/userResource/resource",
			// "consume_record": au + "?mdu=pay&ctl=Index&met=consumeRecord&typ=json",
			"get_consume_record": au + "?mdu=pay&ctl=Index&met=getConsumeRecord&typ=json",
			"consume_deposit": au + "?mdu=pay&ctl=Index&met=consumeDeposit&typ=json",
			// "consume_trade": au + "?mdu=pay&ctl=Index&met=consumeTrade&typ=json",
			"consume_trade": ip + "pay/index/consumeTrade",
			"consume_trade_detail": au + "?mdu=pay&ctl=Index&met=getConsumeTradeDetail&typ=json",
			// "consume_withdraw": au + "?mdu=pay&ctl=Index&met=consumeWithdraw&typ=json",
			"consume_withdraw": ip + "/front/pay/index/consumeWithdrawList",
			"consume_withdraw_info": au + "?mdu=pay&ctl=Index&met=withdrawInfo&typ=json",
			// "consume_withdraw_add": au + "?mdu=pay&ctl=Index&met=addWithdraw&typ=json",
			"consume_withdraw_add": ip + "pay/index/addWithdraw",
			"addCard": au + "?mdu=pay&ctl=Card&met=addCard&typ=json",
			"cardHistory": au + "?mdu=pay&ctl=Card&met=cardHistory&typ=json",
			"reset_paypasswd": au + "?mdu=pay&ctl=Index&met=resetPayPassword&typ=json",
			// "change_paypasswd": au + "?mdu=pay&ctl=Index&met=changePayPassword&typ=json",
			"change_paypasswd": ip + "/front/pay/index/changePayPassword",
			"receive_qrcode": au + "?mdu=pay&ctl=Index&met=receiveQrcode&typ=json",
			"transfer": au + "?mdu=pay&ctl=Index&met=transfer&typ=json",
			"transfer_user_row": au + "?mdu=pay&ctl=Index&met=transferUserRow&typ=json",

			// "list_user_bank": au + "?mdu=pay&ctl=Index&met=listUserBank&typ=json",
			"list_user_bank": ip + "/front/pay/userBank/list",
			// "get_user_bank": au + "?mdu=pay&ctl=Index&met=getUserBank&typ=json",
			"get_user_bank": ip + "/front/pay/userBank/get",
			// "add_user_bank": au + "?mdu=pay&ctl=Index&met=addUserBank&typ=json",
			"add_user_bank": ip + "/front/pay/userBank/addOrEditUserBank",
			// "edit_user_bank": au + "?mdu=pay&ctl=Index&met=editUserBank&typ=json",
			"edit_user_bank": ip + "/front/pay/userBank/addOrEditUserBank",
			// "remove_user_bank": au + "?mdu=pay&ctl=Index&met=removeUserBank&typ=json"
			"remove_user_bank": ip + "/front/pay/userBank/remove"
		},
		"exchange": {
			"sp_exchange": au + "?mdu=exchange&ctl=Sp&met=exchange&typ=json",
			"sp_transfer": au + "?mdu=exchange&ctl=Sp&met=transfer&typ=json",
			"point_transfer": au + "?mdu=exchange&ctl=Sp&met=transferPoint&typ=json",
			"sp_sale": au + "?mdu=exchange&ctl=Sp&met=sale&typ=json",
			"sp_buy": au + "?mdu=exchange&ctl=Sp&met=buy&typ=json",
			"bp_exchange": au + "?mdu=exchange&ctl=Bp&met=exchange&typ=json",
			"bp_market": au + "?mdu=exchange&ctl=Bp&met=market&typ=json",
			"sp_history": au + "?mdu=exchange&ctl=Sp&met=listSpHistory&typ=json",
			"sp_trade": au + "?mdu=exchange&ctl=Sp&met=listSpMarket&typ=json",
			"sp_trade_cancel": au + "?mdu=exchange&ctl=Sp&met=cancelSpMarket&typ=json",
			"sp_trade_buy": au + "?mdu=exchange&ctl=Sp&met=buySpMarket&typ=json",
			"do_sp_exchange": au + "?mdu=exchange&ctl=Sp&met=doSpExchange&typ=json",
			"do_sp_transfer": au + "?mdu=exchange&ctl=Sp&met=doSpTransfer&typ=json",
			"do_point_transfer": au + "?mdu=exchange&ctl=Sp&met=doPointTransfer&typ=json",
			"do_sp_sale": au + "?mdu=exchange&ctl=Sp&met=doSpSale&typ=json",
			"bp_history": au + "?mdu=exchange&ctl=Bp&met=listBpHistory&typ=json",
			"do_bp_exchange": au + "?mdu=exchange&ctl=Bp&met=doBpExchange&typ=json",
			"do_bp_market": au + "?mdu=exchange&ctl=Bp&met=doBpMarket&typ=json",
			"funds_lists": au + "?mdu=exchange&ctl=Funds&met=listFunds&typ=json",
			"funds_profit_lists": au + "?mdu=exchange&ctl=Funds&met=listFundsProfit&typ=json"
		},
		"fx": {
			"invite": iu + "?ctl=Distribution_User&met=invite&typ=json",
			// "poster": iu + "?ctl=Distribution_User&met=poster&typ=json",
			poster: ip + "/front/trade/distribution/poster",
			// "withdraw": iu + "?ctl=Distribution_User&met=withdraw&typ=json",
			"withdraw": ip + "/front/trade/distribution/withdraw",
			//"doWithdraw": iu + "?ctl=Distribution_User&met=doWithdraw&typ=json",
			"doWithdraw": ip + "/front/trade/distribution/doWithdraw",
			"doWithdrawMoney": ip + "/front/trade/distribution/doWithdrawMoney",
			"lists": iu + "?ctl=Distribution_User&met=lists&typ=json",
			// "lists_commission": iu + "?ctl=Distribution_User&met=listsCommission&typ=json",
			lists_commission: ip + "/front/trade/distribution/listsCommission",
			get_commission_order_num: ip + "/front/trade/distribution/getCommissionNum",
			"lists_team": iu + "?ctl=Distribution_User&met=listsTeam&typ=json",
			// "lists_order": iu + "?ctl=Distribution_User&met=listsOrder&typ=json",
			lists_order: ip + "/front/trade/distribution/listsOrder",
			index: ip + "/front/trade/distribution/index",
			// "getCommissionTimeline": iu + "?ctl=Distribution_User&met=getCommissionTimeline&typ=json"
			getCommissionTimeline: ip + "/front/trade/distribution/getCommissionTimeline",
		},
		"admin": {
			"pay": {
				"orderRecord": mu + "?mdu=pay&ctl=Consume_Record&met=orderRecord&typ=json",
				// "offline": mu + "?mdu=pay&ctl=Consume_Trade&met=offline&typ=json"
				"offline": mu + "/admin/pay/pay-consume-trade/offline"
			},
			"lists": {
				// "payment_channel": mu + "?ctl=Category&met=lists&typ=json&isDelete=2&type_number=payment_channel_id",
				"payment_channel": mu + "/admin/pay/pay-payment-channel/list",
				"express": mu + "?ctl=Category&met=lists&typ=json&isDelete=2&type_number=express_id"
			}
		},
		"sns": {
			"story_timeline_lists": au + "?mdu=sns&ctl=Story_Timeline&met=lists&typ=json",
			// "story_lists": au + "?mdu=sns&ctl=Story&met=lists&typ=json",
			"story_lists": ip + "sns/Story/lists",
			// "story_get": au + "?mdu=sns&ctl=Story&met=get&typ=json",
			"story_get": ip + "sns/Story/getStory",
			//story_add": au + "?mdu=sns&ctl=Story_Base&met=add&typ=json",
			"story_add": ip + "sns/Story/add",
			"story_remove": ip + "sns/Story/remove",
			"story_edit": au + "?mdu=sns&ctl=Story_Base&met=edit&typ=json",
			// "story_comment_add": au + "?mdu=sns&ctl=Story_Comment&met=add&typ=json",
			"story_comment_add": ip + "sns/Comment/addComment",
			"story_comment_remove": au + "?mdu=sns&ctl=Story_Comment&met=remove&typ=json",
			// "story_comment_lists": au + "?mdu=sns&ctl=Story&met=listComment&typ=json",
			"story_comment_lists": ip + "sns/Story/listComment",
			// "story_rel_data": au + "?mdu=sns&ctl=Story&met=getRelData&typ=json",
			"story_rel_data": ip + "sns/Story/getRelData",
			// "category_lists": au + "?mdu=sns&ctl=Story&met=listCategory&typ=json",
			"category_lists": ip + "sns/Story/listCategory",
			// "category_get": au + "?mdu=sns&ctl=Story&met=getCategory&typ=json",
			"category_get": ip + "sns/Story/getCategory",
			// "story_collection_add": au + "?mdu=sns&ctl=Story_Collection&met=add&typ=json",
			"story_collection_add": ip + "sns/collection/add",
			// "story_collection_remove": au + "?mdu=sns&ctl=Story_Collection&met=remove&typ=json",
			"story_collection_remove": ip + "sns/collection/remove",
			// "story_like_add": au + "?mdu=sns&ctl=Story_Like&met=add&typ=json",
			"story_like_add": ip + "sns/Like/add",
			// "story_like_remove": au + "?mdu=sns&ctl=Story_Like&met=remove&typ=json",
			"story_like_remove": ip + "sns/Like/remove",
			// "story_comment_like_add": au + "?mdu=sns&ctl=Story_Comment&met=like&typ=json",
			"story_comment_like_add": ip + "sns/Like/like",
			// "story_comment_like_remove": au + "?mdu=sns&ctl=Story_Comment&met=unlike&typ=json",
			"story_comment_like_remove": ip + "sns/Like/unlike",

			// "story_comment_reply_like_add": au + "?mdu=sns&ctl=Story_Comment&met=likeReply&typ=json",
			"story_comment_reply_like_add": ip + "sns/Like/likeReply",
			// "story_comment_reply_like_remove": au + "?mdu=sns&ctl=Story_Comment&met=unlikeReply&typ=json",
			"story_comment_reply_like_remove": ip + "sns/Like/unlikeReply",
			// "user_space": au + "?mdu=sns&ctl=Story&met=space&typ=json",
			"user_space": ip + "sns/Story/space",
			// "user_story": au + "?mdu=sns&ctl=Story&met=story&typ=json",
			"user_story": ip + "sns/Story/story",
			// "user_comment_story": au + "?mdu=sns&ctl=Story&met=listUserCommentStory&typ=json",
			"user_comment_story": ip + "sns/Comment/listUserCommentStory",
			// "user_collect_story": au + "?mdu=sns&ctl=Story&met=listUserCollectStory&typ=json",
			"user_collect_story": ip + "sns/Story/listUserCollectStory",
		},
		"seller": {
			"vehicle_category": mu + "?mdu=&ctl=Base_VehicleCategory&met=tree&typ=json",
			// "User_Info": mu + "?mdu=account&ctl=User_Info&met=lists&typ=json",
			"User_Info": mu + "/admin/account/account-user-base/list",
			"treeleaf": iu + "?ctl=Product&met=treeleaf&typ=json",
			// "checkout": mu + "?mdu=seller&ctl=Order_Base&met=checkout&typ=json",
			"checkout": ip + "/front/trade/cart/checkout",
			// "select_Clerk": mu + "?mdu=seller&ctl=Store_Employee&met=lists&typ=json",
			"select_Clerk": mu + "/admin/shop/shop-store-employee/list",
			"add_member": mu + "?mdu=invoicing&ctl=Customer_Base&met=add&typ=json",
			"product_category": mu + "?mdu=seller&ctl=Base_ProductCategory&met=treeview&typ=json",
			// "edit_quantity": mu + "?mdu=seller&ctl=Product_Base&met=saveQuantity&typ=json",
			"edit_quantity": mu + "/admin/shop/shop-product-item/saveQuantity",
			// "add_DistProduct": mu + "?mdu=&ctl=Product_Base&met=addDistProduct&typ=json",
			"add_DistProduct": ip + "shop/shop-product-base/addDistProduct",
			// "product_pool": mu + "?mdu=&ctl=Product_Base&met=lists&typ=json",
			"product_pool": ip + "shop/shop-product-base/sellerProductList",
			// "Order_Base": mu + "?mdu=seller&ctl=Order_Base&met=add&typ=json",
			"Order_Base": mu + "/admin/shop/shop-order-base/add",
			"User_DeliveryAddress": mu + "?mdu=seller&ctl=User_DeliveryAddress&met=lists&typ=json",
			// "store": mu + "?mdu=seller&ctl=Store_Base&met=get&typ=json",
			"store": ip + "shop/store/getStore",
			"product": mu + "?mdu=seller&ctl=Product&met=lists&typ=json",
			"product_add": mu + "?mdu=seller&ctl=Product&met=add&typ=json",
			// "add_product": mu + "?mdu=seller&ctl=Product_Base&met=add&typ=json",
			"add_product": mu + "/admin/shop/shop-product-base/saveProduct",
			// "get_store_info": mu + "?mdu=seller&ctl=Store_Base&met=get&typ=json",
			"get_store_info": ip + "shop/store/getStore",
			// "edit_store_info": mu + "?mdu=seller&ctl=Store_Base&met=edit&typ=json",
			"edit_store_info": ip + "shop/store/editStore",
			// "lists_item": mu + "?mdu=seller&ctl=Product_Item&met=lists&typ=json",
			"lists_item": mu + "/admin/shop/shop-product-item/list",
			// "lists_product": mu + "?mdu=seller&ctl=Product_Base&met=lists&typ=json",
			"lists_product": ip + "shop/shop-product-base/sellerProductList",
			"edit_state": mu + "/admin/shop/shop-product-base/editState",
			"remove_product": mu + "/admin/shop/shop-product-base/delete",
			"dashboard": mu + "/admin/shop/shop-order-info/dashboard",
			// "dashboard": mu + "?mdu=seller&ctl=Index&met=dashboard&typ=json",
			// "order_lists": mu + "?mdu=seller&ctl=Order_Base&met=listsOrderAndsProduct&typ=json",
			"order_lists": ip + "shop/userOrder/listsOrderAndsProduct",
			"edit_fee": mu + "?mdu=seller&ctl=Order_Base&met=editFee&typ=json",
			//"edit_discount": mu + "?mdu=seller&ctl=Order_Base&met=editDiscount&typ=json",
			"edit_discount": mu + "/admin/shop/shop-order-base/editFee",
			// "review": mu + "?mdu=seller&ctl=Order_Base&met=review&typ=json",
			"review": mu + "/admin/shop/shop-order-base/review",
			// "review_finance": mu + "?mdu=seller&ctl=Order_Base&met=reviewFinance&typ=json",
			"review_finance": mu + "/admin/shop/shop-order-base/reviewFinance",
			// "review_picking": mu + "?mdu=seller&ctl=Order_Base&met=reviewPicking&typ=json",
			"review_picking": mu + "/admin/shop/shop-order-base/reviewPicking",
			"cancel_order": mu + "/admin/shop/shop-order-base/cancel",
			"getOrderStock": mu + "/admin/shop/shop-order-base/getOrderStock",
			"saveOrderLogistics": mu + "/admin/shop/shop-order-logistics/saveOrderLogistics",
			// "lists_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=lists&typ=json",
			"lists_shipping_address": ip + "shop/store/getAddressList",
			// "del_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=remove&typ=json",
			// "add_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=add&typ=json",
			// "edit_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=edit&typ=json",
			// "get_shipping_address": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=get&typ=json",
			"del_shipping_address": ip + "shop/store/delAddress",
			"add_shipping_address": ip + "shop/store/editAddress",
			"edit_shipping_address": ip + "shop/store/editAddress",
			"get_shipping_address": ip + "shop/store/getAddress",
			"get_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=get&typ=json",
			"select_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=selectDefault&typ=json",
			// "enabled_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=selectEnabled&typ=json",
			"enabled_express_logistics": ip + "shop/store/selectEnabled",
			// "lists_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=lists&typ=json",
			"lists_express_logistics": ip + "shop/store/expressLogistics",
			"del_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=remove&typ=json",
			"add_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=add&typ=json",
			"edit_express_logistics": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=edit&typ=json",
			"order_cancel": mu + "?mdu=seller&ctl=Order_Base&met=cancel&typ=json",
			"order_receive": mu + "?mdu=seller&ctl=Order_Base&met=receive&typ=json",
			"order_remove": mu + "?mdu=seller&ctl=Order_Base&met=remove&typ=json",
			"order_detail": mu + "?mdu=seller&ctl=Order_Base&met=detail&typ=json",
			// "order_get_by_pickupcode": mu + "?mdu=seller&ctl=Order_Base&met=getOrderByPickUpCode&typ=json",
			"order_get_by_pickupcode": ip + "shop/userOrder/getOrderByPickUpCode",
			"do_pickup": mu + "/admin/shop/shop-order-chain-code/doPickUp",
			"order_delivery": mu + "?mdu=seller&ctl=Order_Base&met=delivery&typ=json",
			"market_lists": mu + "?mdu=city&ctl=Market_OrderBase&met=lists&typ=json",
			"waybill_tpl_lists": mu + "?mdu=seller&ctl=Store_WaybillTpl&met=lists&typ=json",
			"waybill_tpl_add": mu + "?mdu=seller&ctl=Store_WaybillTpl&met=add&typ=json",
			// "express_logistics_lists": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=lists&typ=json",
			"express_logistics_lists": ip + "/front/sys/express/list",
			"express_logistics_add": mu + "?mdu=seller&ctl=Store_ExpressLogistics&met=add&typ=json",
			// "shipping_address_lists": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=lists&typ=json",
			"shipping_address_lists": ip + "shop/store/getAddressList",
			"shipping_address_add": mu + "?mdu=seller&ctl=Store_ShippingAddress&met=add&typ=json",
			"add_store_book": mu + "?mdu=seller&ctl=Store_Book&met=add&typ=json",
			"lists_store_book": mu + "?mdu=seller&ctl=Store_Book&met=lists&typ=json",
			"del_store_book": mu + "?mdu=seller&ctl=Store_Book&met=remove&typ=json",
			"edit_store_book": mu + "?mdu=seller&ctl=Store_Book&met=edit&typ=json",
			// "getOrderDetail": mu + "?mdu=seller&ctl=Order_Base&met=getOrderDetail&typ=json",
			"getOrderDetail": ip + "shop/userOrder/getOrderDetail",
			"multiUpload": mu + "?mdu=seller&ctl=Order_Item&met=multiUpload&typ=json",
			// "Store_TransportType": mu + "?mdu=seller&ctl=Store_TransportType&met=lists&typ=json",
			"Store_TransportType": ip + 'shop/store/transports',
			//"Store_ProductCategory": mu + "?mdu=seller&ctl=Store_ProductCategory&met=treeview&typ=json",
			"Store_ProductCategory": ip + "shop/store/storeCategoryList",
		},
		"city": {
			// "paotui_info": iu + "?mdu=city&ctl=User_Paotuier&met=info&typ=json",
			"paotui_info": ip + "shop/userPaotuier/info",
			// "paotui_active": iu + "?mdu=city&ctl=User_Paotuier&met=setActive&typ=json",
			"paotui_active": ip + "shop/userPaotuier/setActive",
			"paotui_apply": iu + "?mdu=city&ctl=User_Paotuier&met=add&typ=json",
			// "paotui_order_list": iu + "?mdu=city&ctl=User_Paotuier&met=getOrderList&typ=json",
			"paotui_order_list": ip + "shop/userPaotuier/getOrderList",
			"paotui_finish_order": iu + "?mdu=city&ctl=User_Paotuier&met=getFinishOrderList&typ=json",
			// "paotui_certificate": iu + "?mdu=city&ctl=User_Paotuier&met=saveCertificate&typ=json",
			"paotui_certificate": ip + "shop/userPaotuier/saveCertificate",
			"team_add": iu + "?mdu=city&ctl=Paotui_Team&met=add&typ=json",
			"order_add": iu + "?mdu=city&ctl=Paotui_Order&met=add&typ=json",
			// "order_lists": iu + "?mdu=city&ctl=Paotui_Order&met=lists&typ=json",
			"order_lists": ip + "shop/paotuierOrder/lists",
			"order_apply": iu + "?mdu=city&ctl=Paotui_Order&met=apply&typ=json",
			"order_pickup": iu + "?mdu=city&ctl=Paotui_Order&met=pickup&typ=json",
			"order_signin": iu + "?mdu=city&ctl=Paotui_Order&met=signin&typ=json",
			// "order_get": iu + "?mdu=city&ctl=Paotui_Order&met=get&typ=json",
			"order_get": iu + "shop/paotuierOrder/get",
			"order_remove": iu + "?mdu=city&ctl=Paotui_Order&met=remove&typ=json",
			"receive_order": mu + "?mdu=city&ctl=Market_OrderBase&met=getMarketOrder&typ=json",
			"confirm_receive": mu + "?mdu=city&ctl=Market_OrderBase&met=enable&typ=json",
			"store_Base_list": mu + "?ctl=Store_Base&met=lists&typ=json",
			"transfer_market_order": mu + "?mdu=seller&ctl=Order_Base&met=transferMarketOrder&typ=json",
			"upload_images": mu + "?mdu=seller&ctl=Order_Item&met=updateItemFile&typ=json"
		},
		"hall": {
			//start 采购大厅
			// "purchase_order_lists": iu + "?mdu=hall&ctl=Purchase_OrderBase&met=lists&typ=json",
			"purchase_order_lists": ip + "shop/purchase/lists",
			"get_purchase_order_Detail": iu + "?mdu=hall&ctl=Purchase_OrderBase&met=get&typ=json",
			"save_purchase_order": iu + "?mdu=hall&ctl=Purchase_OrderBase&met=save&typ=json",

			// "user_purchase_order_lists":iu + "?mdu=hall&ctl=User_Purchase&met=listPurchaseOrder&typ=json",
			"user_purchase_order_lists": ip + "shop/purchase/listPurchaseOrder",
			"user_purchase_order": iu + "?mdu=hall&ctl=User_Purchase&met=save&typ=json",
			// "user_purchase_order_get":iu + "?mdu=hall&ctl=User_Purchase&met=get&typ=json",
			"user_purchase_order_get": ip + "shop/purchase/get",
			// "user_purchase_order_index": iu + "?mdu=hall&ctl=User_Purchase&met=index&typ=json",
			"user_purchase_order_index": ip + "shop/purchase/index",
			// "remove_purchase_order": iu + "?mdu=hall&ctl=User_Purchase&met=remove&typ=json",
			"remove_purchase_order": ip + "shop/purchase/remove",
			"user_purchase_order_cancel": iu + "?mdu=hall&ctl=User_Purchase&met=cancelOrder&typ=json",
			"user_purchase_select_supply": iu + "?mdu=hall&ctl=User_Purchase&met=selectSupplyOrder&typ=json",
			"user_purchase_order_check_do": iu + "?mdu=hall&ctl=User_Purchase&met=doOrderCheck&typ=json",

			"supply_order_lists": iu + "?mdu=hall&ctl=Supply_OrderBase&met=lists&typ=json",

			"supply_order_add": iu + "?mdu=hall&ctl=User_Supply&met=addOrder&typ=json",
			"supply_order_check_add": iu + "?mdu=hall&ctl=User_Supply&met=applyOrderCheck&typ=json",
			// "user_supply_order_lists": iu + "?mdu=hall&ctl=User_Supply&met=listSupplyOrder&typ=json",
			"user_supply_order_lists": ip + "shop/supply/listSupplyOrder",
			//end 采购大厅



			"service_order_lists": iu + "?mdu=hall&ctl=Service_OrderBase&met=lists&typ=json",
			"getOrderDetail": iu + "?mdu=hall&ctl=Service_OrderBase&met=get&typ=json",


			"user_service_order_lists": iu + "?mdu=hall&ctl=User_Service&met=listServiceOrder&typ=json",
			"user_service_order_cancel": iu + "?mdu=hall&ctl=User_Service&met=cancelOrder&typ=json",
			"user_service_select_worker": iu + "?mdu=hall&ctl=User_Service&met=selectWorkerOrder&typ=json",
			"user_service_order_check_do": iu + "?mdu=hall&ctl=User_Service&met=doOrderCheck&typ=json",

			"worker_order_lists": iu + "?mdu=hall&ctl=Worker_OrderBase&met=lists&typ=json",

			"worker_order_add": iu + "?mdu=hall&ctl=User_Worker&met=addOrder&typ=json",
			"worker_order_check_add": iu + "?mdu=hall&ctl=User_Worker&met=applyOrderCheck&typ=json",
			"user_worker_order_lists": iu + "?mdu=hall&ctl=User_Worker&met=listWorkerOrder&typ=json",


			"index": iu + "?mdu=hall&ctl=Index&met=index&typ=e",
			"orderForIndex": iu + "?mdu=hall&ctl=Index&met=orderForIndex&typ=e",
			"member": iu + "?mdu=hall&ctl=Index&met=member&typ=e",
			"workerHome": iu + "?mdu=hall&ctl=User_Worker&met=home&typ=e",
			"postAddress": iu + "?mdu=hall&ctl=User_Invoice&met=postAddress&typ=e",
			"companyIndex": iu + "?mdu=hall&ctl=User_Company&met=index&typ=e",
			"companyOrder": iu + "?mdu=hall&ctl=User_Company&met=order&typ=e",
			"companyPayment": iu + "?mdu=hall&ctl=Service_OrderBase&met=payment&typ=e",
			"companyPaymentSuccess": iu + "?mdu=hall&ctl=Service_OrderBase&met=paymentSuccess&typ=e",
			"companyInfo": iu + "?mdu=hall&ctl=User_Company&met=info&typ=e",
			"workerIndex": iu + "?mdu=hall&ctl=User_Worker&met=index&typ=e",
			"workerOrder": iu + "?mdu=hall&ctl=User_Worker&met=order&typ=e",
			"workerInfo": iu + "?mdu=hall&ctl=User_Worker&met=info&typ=e",
			"orderManage": iu + "?mdu=hall&ctl=Service_OrderBase&met=manage&typ=e",
			"workerComment": iu + "?mdu=hall&ctl=User_Worker&met=comment&typ=e",
			"companyComment": iu + "?mdu=hall&ctl=User_Company&met=comment&typ=e",
			"orderDetail": iu + "?mdu=hall&ctl=Service_OrderBase&met=orderDetail&typ=e",
			"editBankCard": iu + "?mdu=hall&ctl=User_BankCard&met=editBankCard&typ=e",
			"delBankCard": iu + "?mdu=hall&ctl=User_BankCard&met=delBankCard&typ=json",
			"myBankCard": iu + "?mdu=hall&ctl=User_BankCard&met=myBankCard&typ=e",
			"getBankList": iu + "?mdu=hall&ctl=User_BankCard&met=getBankList&typ=json",
			"getUserBankList": iu + "?mdu=hall&ctl=User_BankCard&met=getUserBankList&typ=json",
			"saveBankCardInfo": iu + "?mdu=hall&ctl=User_BankCard&met=saveBankCardInfo&typ=json",
			"getTheBankCardInfo": iu + "?mdu=hall&ctl=User_BankCard&met=getTheBankCardInfo&typ=json",
			"isLogin": iu + "?mdu=hall&ctl=Index&met=isHallLogin&typ=json",
			"getCity": iu + "?mdu=hall&ctl=Index&met=getCity&typ=json",
			"scrollPic": iu + "?mdu=hall&ctl=Index&met=scrollPic&typ=json",
			"getStars": iu + "?mdu=hall&ctl=Index&met=getStars&typ=json",
			"getCompanyInfo": iu + "?mdu=hall&ctl=User_Company&met=getCompanyInfo&typ=json",
			"getCodeList": iu + "?mdu=hall&ctl=Index&met=getCodeList&typ=json",
			"saveCompanyValidate": iu + "?mdu=hall&ctl=User_Company&met=saveCompanyValidate&typ=json",
			"saveCompanyInfo": iu + "?mdu=hall&ctl=User_Company&met=saveCompanyInfo&typ=json",
			"isValidateIdentity": iu + "?mdu=hall&ctl=Index&met=isValidateIdentity&typ=json",
			"savePersonValidate": iu + "?mdu=hall&ctl=User_Worker&met=savePersonValidate&typ=json",
			"getAuthorizeSign": iu + "?mdu=hall&ctl=User_Worker&met=getAuthorizeSign&typ=json",
			"getSkill": iu + "?mdu=hall&ctl=User_Worker&met=getSkill&typ=json",
			"completePersonInfo": iu + "?mdu=hall&ctl=User_Worker&met=completePersonInfo&typ=json",
			"saveServiceOrderInfo": iu + "?mdu=hall&ctl=Service_OrderBase&met=saveServiceOrderInfo&typ=json",
			"add_service_order": iu + "?mdu=hall&ctl=Service_OrderBase&met=add&typ=json",
			"orderListPartial": iu + "?mdu=hall&ctl=Service_OrderBase&met=orderListPartial&typ=json",
			"orderListPartialForCompany": iu + "?mdu=hall&ctl=User_Company&met=orderListPartial&typ=json",
			"orderListPartialForWorker": iu + "?mdu=hall&ctl=User_Worker&met=orderListPartial&typ=e",
			"getOrder": iu + "?mdu=hall&ctl=Service_OrderBase&met=getOrder&typ=json",
			"getUserInfo": iu + "?mdu=hall&ctl=User_Worker&met=getUserInfo&typ=json",
			"addService": iu + "?mdu=hall&ctl=User_Service&met=add&typ=json",
			"editService": iu + "?mdu=hall&ctl=User_Service&met=edit&typ=json",
			"getService": iu + "?mdu=hall&ctl=User_Service&met=get&typ=json",
			"delService": iu + "?mdu=hall&ctl=User_Service&met=remove&typ=json",
			"myServiceListPartial": iu + "?mdu=hall&ctl=User_Service&met=lists&typ=json",
			"checkSignUp": iu + "?mdu=hall&ctl=Index&met=checkSingUp&typ=json",
			"getListByCate": iu + "?mdu=hall&ctl=Index&met=getListByCate&typ=json",
			"getHomeData": iu + "?mdu=hall&ctl=Index&met=getHomeData&typ=json",
			"serviceListPartial": iu + "?mdu=hall&ctl=Index&met=serviceListPartial&typ=json",
			"getOrderList": iu + "?mdu=hall&ctl=Index&met=orderForIndex&typ=json",
			//"getOrderDetail":iu + "?mdu=hall&ctl=Service_OrderBase&met=order&typ=json",
			"getWorkerStudio": iu + "?mdu=hall&ctl=Worker_Studio&met=lists&typ=json",
			"checkTax": iu + "?mdu=hall&ctl=Index&met=checkTax&typ=json",
			"signUpListPartial": iu + "?mdu=hall&ctl=Index&met=signUpListPartial&typ=e",
			"saveSignUp": iu + "?mdu=hall&ctl=Index&met=saveSignUp&typ=json",
			"checkChoose": iu + "?mdu=hall&ctl=Index&met=checkChoose&typ=json",
			"cancelSign": iu + "?mdu=hall&ctl=User_Worker&met=cancelSign&typ=json",
			"newBalancePay": iu + "?mdu=hall&ctl=User_Company&met=newBalancePay&typ=json",
			"countTime": iu + "?mdu=hall&ctl=User_Worker&met=countTime&typ=json",
			"requestedChange": iu + "?mdu=hall&ctl=User_Worker&met=requestedChange&typ=json",
			"submitCheck": iu + "?mdu=hall&ctl=User_Worker&met=submitCheck&typ=json",
			"getSignUpInfo": iu + "?mdu=hall&ctl=User_Company&met=getSignUpInfo&typ=json",
			"getSignWorker": iu + "?mdu=hall&ctl=User_Company&met=getSignWorker&typ=json",
			"getUserBank": iu + "?mdu=hall&ctl=User_Invoice&met=getUserBank&typ=json",
			"savePostAddress": iu + "?mdu=hall&ctl=User_Invoice&met=savePostAddress&typ=json",
			"getPostAddress": iu + "?mdu=hall&ctl=User_Invoice&met=getPostAddress&typ=json",
			"delPostAddress": iu + "?mdu=hall&ctl=User_Invoice&met=delPostAddress&typ=json",
			"saveEmail": iu + "?mdu=hall&ctl=User_Invoice&met=saveEmail&typ=json",
			"getEmail": iu + "?mdu=hall&ctl=User_Invoice&met=getEmail&typ=json",
			"delEmail": iu + "?mdu=hall&ctl=User_Invoice&met=delEmail&typ=json",
			"getAddress": iu + "?mdu=hall&ctl=User_Invoice&met=getAddress&typ=json",
			"getAddressByOne": iu + "?mdu=hall&ctl=User_Invoice&met=getAddressByOne&typ=json",
			"getEmails": iu + "?mdu=hall&ctl=User_Invoice&met=getEmails&typ=json",
			"newSubmitQualified": iu + "?mdu=hall&ctl=User_Company&met=newSubmitQualified&typ=json",
			"newSubmitQuaItem": iu + "?mdu=hall&ctl=User_Company&met=newSubmitQuaItem&typ=json",
			"saveJudgeLevelByCompany": iu + "?mdu=hall&ctl=User_Company&met=saveJudgeLevel&typ=json",
			"saveJudgeLevelByWorker": iu + "?mdu=hall&ctl=User_Worker&met=saveJudgeLevel&typ=json",
			"getUserBlanceByNo": iu + "?mdu=hall&ctl=User_Resource&met=getUserBalanceByNo&typ=json",
			"systemMessage": au + "?mdu=sns&ctl=User_Message&met=index&typ=e",
			"getBillsList": iu + "?mdu=hall&ctl=User_Bill&met=index&typ=json",
			"setDefaultPostAddress": iu + "?mdu=hall&ctl=User_Invoice&met=setDefaultPostAddress&typ=json",
			"saveUserBank": iu + "?mdu=hall&ctl=User_Invoice&met=saveUserBank&typ=json",
			"getServiceListForSale": iu + "?mdu=hall&ctl=User_Invoice&met=getServiceListForSale&typ=json",
			"getServiceInfo": iu + "?mdu=hall&ctl=User_Service&met=getServiceInfo&typ=json",
			"addServiceOrder": iu + "?mdu=hall&ctl=User_Service&met=addServiceOrder&typ=json",
			"register": bu + "?mdu=account&ctl=Login&met=register&typ=e",
			"studioLookup": iu + "?mdu=hall&ctl=Worker_Studio&met=studioLookup&typ=json",
			"studioNum": iu + "?mdu=hall&ctl=Worker_Studio&met=studioNum&typ=json"
		},
		"live": {
			//"checkPerm": "https://test.suteshop.com/index.php?mdu=live&ctl=Live&met=checkPerm&typ=json",
			"checkPerm": ip + "sns/Live/checkPerm",
			//"saveRoom": "https://test.suteshop.com/index.php?mdu=live&ctl=Live&met=saveRoom&typ=json",
			"saveRoom": ip + "sns/Live/saveRoom",
			// "index": iu + "?mdu=live&ctl=Live&met=index&typ=json",
			"index": ip + "sns/Live/index",
			"rtc": bu + "/shop/api/rtc.php",
			//xcx直播
			// "applyAnchor":iu + "?mdu=live&ctl=WeixinLive&met=applyAnchor&typ=json",
			"applyAnchor": ip + "/front/live/wxLive/applyAnchor",
			// "anchor":iu + "?mdu=live&ctl=WeixinLive&met=anchor&typ=json",
			"anchor": ip + "/front/live/wxLive/anchor",
			// "createRoom":iu + "?mdu=live&ctl=WeixinLive&met=createRoom&typ=json",
			"createRoom": ip + "/front/live/wxLive/createRoom",
			// "listRoom":iu + "?mdu=live&ctl=WeixinLive&met=listRoom&typ=json",
			"listRoom": ip + "/front/live/wxLive/listRoom",
		},
		"card": {
			"card_list": mu + "/card/pay/pay-card-info/getListByUserid",
			"card_info_get": mu + "/card/pay/pay-card-info/getInfoByCardTypeId"
		}
	},
	"tabBar": {
		"color": "#7A7E83",
		"borderStyle": "black",
		"backgroundColor": "#ffffff",

		"selectedColor": "#A76E38",
		"list": [{
				"pagePath": "pages/index/index",
				"iconPath": "static/images/tabBar1.png",
				"selectedIconPath": "static/images/tabBar_sel1.png",
				"text": "首页"
			},
			{
				"pagePath": "pages/category/category",
				"iconPath": "static/images/tabBar2.png",
				"selectedIconPath": "static/images/tabBar_sel2.png",
				"text": "分类"
			},
			{
				"pagePath": "pages/cart/cart",
				"iconPath": "static/images/tabBar3.png",
				"selectedIconPath": "static/images/tabBar_sel3.png",
				"text": "购物车"
			},
			{
				"pagePath": "pages/index/member",
				"iconPath": "static/images/tabBar4.png",
				"selectedIconPath": "static/images/tabBar_sel4.png",
				"text": "我的"
			}
		]
	}
}
